<?php /** EnginesisErrors.php
 * DO NOT EDIT THIS FILE - it is generated by procedure.
 *
 * Date generated: 3-Jan-2021 01:13:31 PM
 */

abstract class EnginesisErrors {
    const NO_ERROR = '';
    const ALREADY_ASSIGNED = 'ALREADY_ASSIGNED';
    const ALREADY_CONFIRMED = 'ALREADY_CONFIRMED';
    const ALREADY_GIFTED = 'ALREADY_GIFTED';
    const ALREADY_GIFTED_MAX = 'ALREADY_GIFTED_MAX';
    const BAD_GAME_ID = 'BAD_GAME_ID';
    const CANNOT_CHANGE_GAME_NAME_TO_EXISTING_GAME_NAME = 'CANNOT_CHANGE_GAME_NAME_TO_EXISTING_GAME_NAME';
    const CANNOT_CHANGE_QUIZ_TITLE_TO_EXISTING_TITLE = 'CANNOT_CHANGE_QUIZ_TITLE_TO_EXISTING_TITLE';
    const CANNOT_COMMENT_YOURSELF = 'CANNOT_COMMENT_YOURSELF';
    const CANNOT_GIFT_YOURSELF = 'CANNOT_GIFT_YOURSELF';
    const CANNOT_IDENTIFY_USER = 'CANNOT_IDENTIFY_USER';
    const CANNOT_MOVE_FILE = 'CANNOT_MOVE_FILE';
    const CANNOT_PURCHASE_ITEM = 'CANNOT_PURCHASE_ITEM';
    const CANNOT_SET_SESSION = 'CANNOT_SET_SESSION';
    const CMS_LOCKED = 'CMS_LOCKED';
    const COMMENT_DOES_NOT_EXIST = 'COMMENT_DOES_NOT_EXIST';
    const CREDIT_FAILED = 'CREDIT_FAILED';
    const DATABASE_CONNECT_ERROR = 'DATABASE_CONNECT_ERROR';
    const DATABASE_ERROR = 'DATABASE_ERROR';
    const DEBUG_STMT = 'DEBUG_STMT';
    const DUPLICATE_ENTRY = 'DUPLICATE_ENTRY';
    const EMAIL_IN_USE = 'EMAIL_IN_USE';
    const ERROR_CREATING_QUIZ = 'ERROR_CREATING_QUIZ';
    const ERROR_IN_MAINTDAILY = 'ERROR_IN_MAINTDAILY';
    const ERROR_IN_PACK_CONTENT = 'ERROR_IN_PACK_CONTENT';
    const ERROR_NOT_DEFINED = 'ERROR_NOT_DEFINED';
    const ERROR_SAVING_QUIZ_ATTRIBUTES = 'ERROR_SAVING_QUIZ_ATTRIBUTES';
    const ERROR_UPDATING_QUIZ = 'ERROR_UPDATING_QUIZ';
    const FILE_EXCEPTION = 'FILE_EXCEPTION';
    const FILE_NOT_FOUND = 'FILE_NOT_FOUND';
    const FILE_WRITE_FAILED = 'FILE_WRITE_FAILED';
    const GAME_DATA_FOLDER_NOT_WRITABLE = 'GAME_DATA_FOLDER_NOT_WRITABLE';
    const GAME_GROUP_ALREADY_EXISTS = 'GAME_GROUP_ALREADY_EXISTS';
    const GAME_ID_IN_USE = 'GAME_ID_IN_USE';
    const GAME_ID_NOT_IN_ANY_GROUPS = 'GAME_ID_NOT_IN_ANY_GROUPS';
    const GAME_NAME_IN_USE = 'GAME_NAME_IN_USE';
    const GAME_NOT_ASSIGNED = 'GAME_NOT_ASSIGNED';
    const GIFT_ALREADY_UNLOCKED = 'GIFT_ALREADY_UNLOCKED';
    const GIFT_EXISTS = 'GIFT_EXISTS';
    const GIFT_IS_LOCKED = 'GIFT_IS_LOCKED';
    const ID_IN_USE = 'ID_IN_USE';
    const INCOMPLETE = 'INCOMPLETE';
    const INSUFFICIENT_ACCESS = 'INSUFFICIENT_ACCESS';
    const INVALID_CATEGORY_ID = 'INVALID_CATEGORY_ID';
    const INVALID_CATEGORY_KEY = 'INVALID_CATEGORY_KEY';
    const INVALID_CONTENT = 'INVALID_CONTENT';
    const INVALID_COREG_TYPE = 'INVALID_COREG_TYPE';
    const INVALID_DATA = 'INVALID_DATA';
    const INVALID_DEVELOPER_KEY = 'INVALID_DEVELOPER_KEY';
    const INVALID_FILE = 'INVALID_FILE';
    const INVALID_FROM_ADDRESS = 'INVALID_FROM_ADDRESS';
    const INVALID_GAME_ID = 'INVALID_GAME_ID';
    const INVALID_GIFT_ID = 'INVALID_GIFT_ID';
    const INVALID_GIFT_METHOD_TYPE = 'INVALID_GIFT_METHOD_TYPE';
    const INVALID_ID = 'INVALID_ID';
    const INVALID_LIST = 'INVALID_LIST';
    const INVALID_LOGIN = 'INVALID_LOGIN';
    const INVALID_MESSAGE = 'INVALID_MESSAGE';
    const INVALID_NAME = 'INVALID_NAME';
    const INVALID_PARAMETER = 'INVALID_PARAMETER';
    const INVALID_PASSWORD = 'INVALID_PASSWORD';
    const INVALID_QUIZ_CHOICE_ID = 'INVALID_QUIZ_CHOICE_ID';
    const INVALID_QUIZ_QUESTION_ID = 'INVALID_QUIZ_QUESTION_ID';
    const INVALID_SECONDARY_PASSWORD = 'INVALID_SECONDARY_PASSWORD';
    const INVALID_SERVICE_REQUEST = 'INVALID_SERVICE_REQUEST';
    const INVALID_SESSION = 'INVALID_SESSION';
    const INVALID_SITE_ID = 'INVALID_SITE_ID';
    const INVALID_SITE_NAME = 'INVALID_SITE_NAME';
    const INVALID_SITE_USER_ID = 'INVALID_SITE_USER_ID';
    const INVALID_TAG = 'INVALID_TAG';
    const INVALID_TITLE = 'INVALID_TITLE';
    const INVALID_TOKEN = 'INVALID_TOKEN';
    const INVALID_TO_ADDRESS = 'INVALID_TO_ADDRESS';
    const INVALID_USER_ID = 'INVALID_USER_ID';
    const IO_ERROR = 'IO_ERROR';
    const LOGIN_SYSTEM_ERROR = 'LOGIN_SYSTEM_ERROR';
    const MISSING_PARAM = 'MISSING_PARAM';
    const NAME_IN_USE = 'NAME_IN_USE';
    const NAME_UNKNOWN = 'NAME_UNKNOWN';
    const NOT_AUTHENTICATED = 'NOT_AUTHENTICATED';
    const NOT_AUTHORIZED = 'NOT_AUTHORIZED';
    const NOT_ENOUGH_EXP = 'NOT_ENOUGH_EXP';
    const NOT_IMPLEMENTED = 'NOT_IMPLEMENTED';
    const NOT_LOGGED_IN = 'NOT_LOGGED_IN';
    const NOT_SUBSCRIBED = 'NOT_SUBSCRIBED';
    const NOT_YOUR_COMMENT = 'NOT_YOUR_COMMENT';
    const NO_COMMENT = 'NO_COMMENT';
    const NO_CONTENT = 'NO_CONTENT';
    const NO_MATCHING_ITEM = 'NO_MATCHING_ITEM';
    const PASSWORD_EXPIRED = 'PASSWORD_EXPIRED';
    const QUIZ_ERROR = 'QUIZ_ERROR';
    const QUIZ_NOT_SCHEDULED_AT_THIS_TIME = 'QUIZ_NOT_SCHEDULED_AT_THIS_TIME';
    const QUIZ_RESULTS_DATA_ERROR = 'QUIZ_RESULTS_DATA_ERROR';
    const QUIZ_TITLE_MUST_BE_UNIQUE = 'QUIZ_TITLE_MUST_BE_UNIQUE';
    const REGISTRATION_NOT_CONFIRMED = 'REGISTRATION_NOT_CONFIRMED';
    const SECURITY_ERROR = 'SECURITY_ERROR';
    const SEND_ERROR = 'SEND_ERROR';
    const SERVER_DID_NOT_REPLY = 'SERVER_DID_NOT_REPLY';
    const SERVER_RESPONSE_NOT_VALID = 'SERVER_RESPONSE_NOT_VALID';
    const SERVICE_ERROR = 'SERVICE_ERROR';
    const SESSION_EXPIRED = 'SESSION_EXPIRED';
    const SITE_NAME_IN_USE = 'SITE_NAME_IN_USE';
    const SOCIAL_SERVICE_ERROR = 'SOCIAL_SERVICE_ERROR';
    const SUBMIT_ERROR = 'SUBMIT_ERROR';
    const SYSTEM_ERROR = 'SYSTEM_ERROR';
    const TOKEN_EXPIRED = 'TOKEN_EXPIRED';
    const TOO_MANY_ITEMS = 'TOO_MANY_ITEMS';
    const UNDEFINED_KEY = 'UNDEFINED_KEY';
    const UNKNOWN_SERVICE = 'UNKNOWN_SERVICE';
    const UPDATED = 'UPDATED';
    const USER_BLOCKED = 'USER_BLOCKED';
    const USER_DOES_NOT_EXIST = 'USER_DOES_NOT_EXIST';
    const VALIDATION_FAILED = 'VALIDATION_FAILED';

    static function isError($errorCode) {
        return $errorCode != EnginesisErrors::NO_ERROR;
    }
}

$errorCodeTable = [
    EnginesisErrors::ALREADY_ASSIGNED => 'The object was previously assigned to this user.',
    EnginesisErrors::ALREADY_CONFIRMED => 'This user previously confirmed registration.',
    EnginesisErrors::ALREADY_GIFTED => 'This user already has that gift.',
    EnginesisErrors::ALREADY_GIFTED_MAX => 'The user already has the maximum number of gifts allowed for this item.',
    EnginesisErrors::BAD_GAME_ID => 'The game id provided is not of the appropriate format.',
    EnginesisErrors::CANNOT_CHANGE_GAME_NAME_TO_EXISTING_GAME_NAME => 'The new game name specified already identifies an existing game. Game names must be unique.',
    EnginesisErrors::CANNOT_CHANGE_QUIZ_TITLE_TO_EXISTING_TITLE => 'The quiz title specified already identifies an existing quiz. Quiz titles must be unique.',
    EnginesisErrors::CANNOT_COMMENT_YOURSELF => 'You cannot assign a comment to yourself.',
    EnginesisErrors::CANNOT_GIFT_YOURSELF => 'You cannot give that gift to yourself.',
    EnginesisErrors::CANNOT_IDENTIFY_USER => 'The information provided does not identify a user.',
    EnginesisErrors::CANNOT_MOVE_FILE => 'File copy or move operation failed.',
    EnginesisErrors::CANNOT_PURCHASE_ITEM => 'The item you attempted to purchase is not for sale.',
    EnginesisErrors::CANNOT_SET_SESSION => 'The Enginesis session cannot be established. Probably a HTTP protocol violation.',
    EnginesisErrors::CMS_LOCKED => 'Enginesis CMS is locked. Try again later.',
    EnginesisErrors::COMMENT_DOES_NOT_EXIST => 'The information provided does not identify a comment.',
    EnginesisErrors::CREDIT_FAILED => 'You do not have enough currency to purchase the item requested.',
    EnginesisErrors::DATABASE_CONNECT_ERROR => 'Could not connect to the database server. Check network access and login credentials.',
    EnginesisErrors::DATABASE_ERROR => 'Internal system error while trying to perform the requested service.',
    EnginesisErrors::DEBUG_STMT => 'Trace message',
    EnginesisErrors::DUPLICATE_ENTRY => 'Object or data already exists matching that identity.',
    EnginesisErrors::EMAIL_IN_USE => 'The email address is already used by another account.',
    EnginesisErrors::ERROR_CREATING_QUIZ => 'An error occurred creating the quiz.',
    EnginesisErrors::ERROR_IN_MAINTDAILY => 'An error occurred in daily maintenance processing. Please check the logs.',
    EnginesisErrors::ERROR_IN_PACK_CONTENT => 'The data packet provided is not of the expected format.',
    EnginesisErrors::ERROR_NOT_DEFINED => 'The error code specified is not defined.',
    EnginesisErrors::ERROR_SAVING_QUIZ_ATTRIBUTES => 'An error occurred saving the quiz attributes.',
    EnginesisErrors::ERROR_UPDATING_QUIZ => 'An error occurred updating the quiz.',
    EnginesisErrors::FILE_EXCEPTION => 'An exception occurred on the requested file.',
    EnginesisErrors::FILE_NOT_FOUND => 'The requested file was not found. Check your entry.',
    EnginesisErrors::FILE_WRITE_FAILED => 'Could not write the file.',
    EnginesisErrors::GAME_DATA_FOLDER_NOT_WRITABLE => 'Could not write to the game data folder. Check configuration and access rights.',
    EnginesisErrors::GAME_GROUP_ALREADY_EXISTS => 'The name provided already identifies an existing game group. Game group names must be unique.',
    EnginesisErrors::GAME_ID_IN_USE => 'The specified game id is already in use in this context.',
    EnginesisErrors::GAME_ID_NOT_IN_ANY_GROUPS => 'The game id specified does not belong to any game groups.',
    EnginesisErrors::GAME_NAME_IN_USE => 'The name provided already identifies an existing game. Game names must be unique.',
    EnginesisErrors::GAME_NOT_ASSIGNED => 'The game was not assigned to the game group.',
    EnginesisErrors::GIFT_ALREADY_UNLOCKED => 'You previously unlocked this gift.',
    EnginesisErrors::GIFT_EXISTS => 'A gift with that name or id already exists.',
    EnginesisErrors::GIFT_IS_LOCKED => 'The gift is lock you must purchase it before you may give it out.',
    EnginesisErrors::ID_IN_USE => 'The identifier provided is already assigned to another object.',
    EnginesisErrors::INCOMPLETE => 'The service began execution but was not able to finish.',
    EnginesisErrors::INSUFFICIENT_ACCESS => 'You do not have access rights to perform this request.',
    EnginesisErrors::INVALID_CATEGORY_ID => 'The category identifier provided is not valid.',
    EnginesisErrors::INVALID_CATEGORY_KEY => 'The category key provided is not valid in the context of the category id.',
    EnginesisErrors::INVALID_CONTENT => 'The content provided is not valid. Please check character and tag restrictions.',
    EnginesisErrors::INVALID_COREG_TYPE => 'The co-registration type specified is not defined.',
    EnginesisErrors::INVALID_DATA => 'The data provided is either missing, invalid, out of range, or not properly formatted.',
    EnginesisErrors::INVALID_DEVELOPER_KEY => 'The developer key provided is not valid.',
    EnginesisErrors::INVALID_FILE => 'The content or format of the provided was not valid.',
    EnginesisErrors::INVALID_FROM_ADDRESS => 'A valid from email address must be provided.',
    EnginesisErrors::INVALID_GAME_ID => 'The game id provided is not valid, is not defined, or is not assigned to the site context.',
    EnginesisErrors::INVALID_GIFT_ID => 'The gift id provided is not valid, is not defined, or is not assigned to the site context.',
    EnginesisErrors::INVALID_GIFT_METHOD_TYPE => 'The gift method type id provided is not defined.',
    EnginesisErrors::INVALID_ID => 'The identifier specified is not valid or does not identify an object of this type.',
    EnginesisErrors::INVALID_LIST => 'The list provided is an unrecognized format.',
    EnginesisErrors::INVALID_LOGIN => 'The login credentials provided did not match.',
    EnginesisErrors::INVALID_MESSAGE => 'The message content provided was not valid.',
    EnginesisErrors::INVALID_NAME => 'The name specified cannot be used to identify this type of object.',
    EnginesisErrors::INVALID_PARAMETER => 'One or more parameters provided are not the expected format.',
    EnginesisErrors::INVALID_PASSWORD => 'The login credentials provided did not match.',
    EnginesisErrors::INVALID_QUIZ_CHOICE_ID => 'The quiz choice selected is not valid.',
    EnginesisErrors::INVALID_QUIZ_QUESTION_ID => 'The quiz question selected is not valid.',
    EnginesisErrors::INVALID_SECONDARY_PASSWORD => 'Your confirmation token is not valid or it has expired.',
    EnginesisErrors::INVALID_SERVICE_REQUEST => 'The requested service is not defined.',
    EnginesisErrors::INVALID_SESSION => 'The session you are trying to use is not valid or it has expired.',
    EnginesisErrors::INVALID_SITE_ID => 'The site identifier specified is not defined.',
    EnginesisErrors::INVALID_SITE_NAME => 'The name provided cannot be used as a site context name.',
    EnginesisErrors::INVALID_SITE_USER_ID => 'The identifier provided cannot be used to uniquely identify a user.',
    EnginesisErrors::INVALID_TAG => 'One or more tags violate content or character restrictions.',
    EnginesisErrors::INVALID_TITLE => 'The content provided is not valid as a title.',
    EnginesisErrors::INVALID_TOKEN => 'The token you are trying to use is not valid.',
    EnginesisErrors::INVALID_TO_ADDRESS => 'At least one valid to email address must be provided.',
    EnginesisErrors::INVALID_USER_ID => 'The user id provided is not valid, is not defined, or is not assigned to the site context.',
    EnginesisErrors::IO_ERROR => 'Could not contact server or server replied with an unidentifed result.',
    EnginesisErrors::LOGIN_SYSTEM_ERROR => 'Internal system error while trying to login.',
    EnginesisErrors::MISSING_PARAM => 'A necessary parameter was missing, not identified, or improperly formatted.',
    EnginesisErrors::NAME_IN_USE => 'The name provided is currently used by another object of this type. Name must be unique.',
    EnginesisErrors::NAME_UNKNOWN => 'The name provided does not identify any object of this type.',
    EnginesisErrors::NOT_AUTHENTICATED => 'An authenticated user is necessary to perform the requested service.',
    EnginesisErrors::NOT_AUTHORIZED => 'You are not authorized to use this service in this manner.',
    EnginesisErrors::NOT_ENOUGH_EXP => 'You do not yet have enough experience to obtain this item.',
    EnginesisErrors::NOT_IMPLEMENTED => 'The requested service is not implemented at this time.',
    EnginesisErrors::NOT_LOGGED_IN => 'The requested service requires a logged in user.',
    EnginesisErrors::NOT_SUBSCRIBED => 'The user or email address provided is not subscribed.',
    EnginesisErrors::NOT_YOUR_COMMENT => 'You do not have the access rights to alter that comment.',
    EnginesisErrors::NO_COMMENT => 'There was no comment provided.',
    EnginesisErrors::NO_CONTENT => 'There was no content provided to fullfill this operation.',
    EnginesisErrors::NO_MATCHING_ITEM => 'No matching item was identified.',
    EnginesisErrors::PASSWORD_EXPIRED => 'Your confirmation token has expired.',
    EnginesisErrors::QUIZ_ERROR => 'Generic error in quiz service.',
    EnginesisErrors::QUIZ_NOT_SCHEDULED_AT_THIS_TIME => 'There is no quiz scheduled during the time period indicated.',
    EnginesisErrors::QUIZ_RESULTS_DATA_ERROR => 'Quiz results were not saved due to an internal error.',
    EnginesisErrors::QUIZ_TITLE_MUST_BE_UNIQUE => 'Another quiz has that same title. Quiz title must be unique.',
    EnginesisErrors::REGISTRATION_NOT_CONFIRMED => 'Registration has not been confirmed.',
    EnginesisErrors::SECURITY_ERROR => 'Security error while attempting to contact server.',
    EnginesisErrors::SEND_ERROR => 'A system error occurred when sending the message.',
    EnginesisErrors::SERVER_DID_NOT_REPLY => 'The service did not respond to our request. Please check your network connection.',
    EnginesisErrors::SERVER_RESPONSE_NOT_VALID => 'The service responded with an unexpected response. Please check your network connection and the operation of the service.',
    EnginesisErrors::SERVICE_ERROR => 'The service responded with an unexpected error. Please check your network connection and the operation of the service.',
    EnginesisErrors::SESSION_EXPIRED => 'The session that was previously set up has now expired. You must reauthenticate.',
    EnginesisErrors::SITE_NAME_IN_USE => 'The name provided already identifies an existing site context. Site names must be unique.',
    EnginesisErrors::SOCIAL_SERVICE_ERROR => 'Request for a social service failed.',
    EnginesisErrors::SUBMIT_ERROR => 'Data provided to a submit service was not correct or missing.',
    EnginesisErrors::SYSTEM_ERROR => 'There was a system error processing your request. Information has been sent to support to remedy the problem.',
    EnginesisErrors::TOKEN_EXPIRED => 'The token you are trying to use is either invalid or it has past its expiration date.',
    EnginesisErrors::TOO_MANY_ITEMS => 'There are too many items in the list, or the list is an unrecognized format.',
    EnginesisErrors::UNDEFINED_KEY => 'The key does not exist. Keys must be defined before they can be assigned a value.',
    EnginesisErrors::UNKNOWN_SERVICE => 'The service requested is not defined.',
    EnginesisErrors::UPDATED => 'Previous score exists but this score is better.',
    EnginesisErrors::USER_BLOCKED => 'The user is blocked from using the system.',
    EnginesisErrors::USER_DOES_NOT_EXIST => 'The information provided does not identify a user in this site context.',
    EnginesisErrors::VALIDATION_FAILED => 'Validation failed.',
];

/**
 * @param $status_msg
 * @return mixed
 */
function errorToLocalString($status_msg) {
    global $errorCodeTable;
    global $language_code;

    if (isset($errorCodeTable[$status_msg])) {
        $status_msg = $errorCodeTable[$status_msg];
    }
    return $status_msg;
}